### ISSUE TITLE
The API not working once again

### ISSUE THREAD

**Issue by puretechglobal-weilun** [gnuns/allOrigins#108]
![image](https://user-images.githubusercontent.com/73866073/196581668-49b7db29-c33a-46a4-8a2b-4f8219f27072.png)

**Comment by yarodevuci** [comment]
yep, same.... @gnuns is server is down?

**Comment by puretechglobal-weilun** [comment]
> @puretechglobal-weilun any ideas for good alternatives ?

I think domain is up again, my side API is working. I will close this case.
