### ISSUE TITLE
dns failure in JSONP mode produces broken unexecutable JSON data

### ISSUE THREAD

**Issue by bulk88** [gnuns/AllOrigins#11]
While experimenting with allorigins, I noticed for a DNS failure, non-existent domain, the server returns HTTP code 400, which causes the JS callback to never execute since proper browsers do not execute JS code from a script element unless its a 2XX code https://www.theguardian.com/info/developer-blog/2012/jul/16/http-status-codes-jsonp .

example:

http://allorigins.us/get?url=https%3A//nx.baddomain.org/gis%3Floc%3DNYK%26_%3D1511810056058&callback=X

```
GET /get?url=https%3A//nx.baddomain.org/gis%3Floc%3DNYK%26_%3D1511810056058&callback=X HTTP/1.1
Host: allorigins.us
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2600.0 Iron Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

HTTP/1.1 400 Bad Request
Server: nginx/1.10.3 (Ubuntu)
Date: Mon, 27 Nov 2017 19:23:19 GMT
Content-Type: application/json
Content-Length: 141
Connection: keep-alive
X-Powered-By: Express
etag: "206367122"

{"error":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"nx.baddomain.org","host":"nx.baddomain.org","port":443}}
```
Since the server DID return JSON, it is probably intended for the client to parse the DNS failure. But there is one more bug, I asked for JSONP, and my callback wrapper "X" function isn't in the output, so that is a 2nd bug. If my browser client was doing CORS the no callback wrapper and non-200 status code is fine, the client JS code will still be able to read and parse the DNS failure JSON block, but for JSONP mode, I need my callback wrapper and a 2XX status code.

**Comment by gnuns** [comment]
Hi, @bulk88! Thank you for reporting. I'll fix this bug soon.
