### ISSUE TITLE
API seems to be down?

### ISSUE THREAD

**Issue by pizzaboy314** [gnuns/allOrigins#110]
`pizzaboy314.github.io/:1 Access to XMLHttpRequest at 'https://api.allorigins.win/get?url=https%3A%2F%2Fmusic.apple.com%2Fus%2Falbum%2Fto-pimp-a-butterfly%2F1440828886' from origin 'https://pizzaboy314.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

either the API is down or it's no longer bypassing CORS policy

[my repo](https://github.com/pizzaboy314/SonemicAppleAlbumParser) is using it

**Comment by pizzaboy314** [comment]
![image](https://user-images.githubusercontent.com/6517950/201370897-1c65b0a6-40fa-4b99-b16d-82bfc9958f95.png)

**Comment by cschoenecker** [comment]
Same issue for me

**Comment by pizzaboy314** [comment]
API is back up
