### ISSUE TITLE
Block api fetching by CORS policy

### ISSUE THREAD

**Issue by getlost01** [gnuns/allOrigins#112]
Access to XMLHttpRequest at 'https://api.allorigins.win/get?url=https://clist.by/api/v2/contest' from origin 'https://api.allorigins.win/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
<img width="1429" alt="Screenshot 2022-12-07 at 3 48 37 PM" src="https://user-images.githubusercontent.com/79409258/206153031-ad5c3ba1-944b-4f56-a168-250cc1c2e697.png">

**Comment by gnuns** [comment]
Hi, @getlost01 @joewilliams200217 @jo5ef @PavelGalaktionov @alexanderhenne @balzafin @Ghassanee
It's online again. If you can, please consider donating any amount to help me maintain this public and free instance up for everyone. 

- [Patreon](https://www.patreon.com/gnuns)
- [Liberapay](https://liberapay.com/gnuns)
- [Paypal](https://www.paypal.com/donate/?hosted_button_id=7S3KJ8CA43DX6)
- [Ko-fi](https://ko-fi.com/gnuns)

Thank you! 😉

**Comment by getlost01** [comment]
Thank you, I appreciate your application.
