### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by Yarnacle** [gnuns/allOrigins#113]
![Screenshot 2022-12-08 08 59 43](https://user-images.githubusercontent.com/109094587/206479870-4b56c6aa-15f2-4ccc-b378-9beb28f1c540.png)
The website seems to be fine, however.

**Comment by gnuns** [comment]
Hi, @Yarnacle 
It's online again. If you can, please consider donating any amount to help me maintain this public and free instance up for everyone. 

- [Patreon](https://www.patreon.com/gnuns)
- [Liberapay](https://liberapay.com/gnuns)
- [Paypal](https://www.paypal.com/donate/?hosted_button_id=7S3KJ8CA43DX6)
- [Ko-fi](https://ko-fi.com/gnuns)

Thank you! 😉
