### ISSUE TITLE
Suspected Phishing

### ISSUE THREAD

**Issue by mike-labX** [gnuns/allOrigins#120]
Hi.

Already several days, starting from 21.02.2023, i get "suspected phishing" warning when i want to use allOrigins to get contents of external web page.

Even examples that are on allOrigins  page - https://allorigins.win - 
raw
Description: Get the raw contents ([CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS))
Example: https://api.allorigins.win/raw?url=https://example.org/

return this warning.

It can be skipped further manually, but if i want to use allOrigins automatically by JavaScript, to get contents of news web sites and to post news data onto my homepage, i cant skip and i get empty response (https://api.allorigins.win/raw?url=https://www.bbc.com/russian).

Sites what i want to fetch - https://www.bbc.com, https://www.bbc.com/russian, lenta.ru. 
Those are certainly not phishing sites.

Can this error be corrected?

If i use "get" instead of "raw" in command address - (https://api.allorigins.win/get?url=https://www.bbc.com/russian) i get response, but this slower than "raw".

Thank You,
Urmas Repinski.

**Comment by hugovdev** [comment]
I'm getting a similar problem with a different site, I hope this can get fixed!

**Comment by evan-labX** [comment]
Hi.

Warning "Suspected Phishing" is removed, error is corrected, thank you.

Now https://api.allorigins.win/raw?url=https://example.org/ returns
Example Domain
This domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.

[More information...](https://www.iana.org/domains/example)
