### ISSUE TITLE
API giving 502 bad gateway error :(

### ISSUE THREAD

**Issue by AlbertoDesastre** [gnuns/allOrigins#131]
Since today at 8:00 GMT aproximately I haven't been able to get a single response from any API using all Origin, although almost for all week was working properly

**Comment by Nass33m** [comment]
Same thing on my side. A '502: Bad gateway' error since 48+ hours

**Comment by MarcCeleiro** [comment]
Same here!

**Comment by lewiz17** [comment]
Same here!

**Comment by intellimat** [comment]
I got the same error!

**Comment by GiuseppeZ88** [comment]
Same here!

**Comment by gnuns** [comment]
Hi, @GiuseppeZ88 @intellimat @lewiz17 @MarcCeleiro @Nass33m @AlbertoDesastre. Everything is working now. :)
