### ISSUE TITLE
502 bad gateway.

### ISSUE THREAD

**Issue by publicsite** [gnuns/allOrigins#137]
I'm getting 502 bad gateway.

Can make a small donation if you get this fixed.

**Comment by jagdish-15** [comment]
I am facing the same issue as well!

**Comment by madfresh** [comment]
also

**Comment by Vulnpire** [comment]
same here as well

**Comment by nycos62** [comment]
same :'(

**Comment by ExInferi** [comment]
I got a 522, but same idea, server issues

**Comment by pizzaboy314** [comment]
this is a regular issue for the domain, would funding help keep the uptime a little better?

**Comment by shivang2607** [comment]
won't cloning the repo and using it help ?

**Comment by jagdish-15** [comment]
> won't cloning the repo and using it help ?

Umm, the server backend can't be copied by cloning right? Just the files in the repo will be cloned, so unfortunately nope!

**Comment by pizzaboy314** [comment]
> won't cloning the repo and using it help ?

in theory yes I could run it locally as a server but that doesn't help if you have a public app and are using the public API

**Comment by shivang2607** [comment]
> > won't cloning the repo and using it help ?
> 
> in theory yes I could run it locally as a server but that doesn't help if you have a public app and are using the public API

But you can deploy it somewhere like onrender and then use it, right ?

**Comment by pizzaboy314** [comment]
> > > won't cloning the repo and using it help ?
> > 
> > 
> > in theory yes I could run it locally as a server but that doesn't help if you have a public app and are using the public API
> 
> But you can deploy it somewhere like onrender and then use it, right ?

I mean go for it man

**Comment by pizzaboy314** [comment]
> I'm getting 502 bad gateway.
> 
> Can make a small donation if you get this fixed.

<img width="373" alt="{8B6AE18B-1118-4335-ABC6-E5D3FB82C046}" src="https://github.com/user-attachments/assets/2304db2d-b006-4278-bd38-9494cceffd09">

[he has a Patreon for this looks like](https://www.patreon.com/c/gnuns)

**Comment by gnuns** [comment]
It's back online. Thanks for reporting. If you can, please donate to help me keep the server online! Any amount is appreciated (:

**Comment by publicsite** [comment]
Done and Done :+1:
