### ISSUE TITLE
Responding with the actual status code

### ISSUE THREAD

**Issue by tobihagemann** [gnuns/AllOrigins#17]
Consider the following setup: Deploying AllOrigins on a server that has caching activated. For example, using this feature in NGINX: https://www.nginx.com/blog/nginx-caching-guide/#stale

The thing is now that caching doesn't work for errors because AllOrigins always responds with status code `200`. Therefore, NGINX caches the error page even though it should handle it as a stale response.

I understand that it could make sense because AllOrigins's service indeed responds successfully but I think that AllOrigins should be considered a _transparent_ proxy. At least that's what it's probably used for in most cases.

My proposal is to add `res.status(page.status.http_code)` somewhere in this method: https://github.com/gnuns/AllOrigins/blob/e170b6adbb8f538d71356c1e540e5c67f1f5dece/lib/index.js#L14

Please let me know what you think.

**Comment by gnuns** [comment]
It makes sense on requests using `method=raw`, but on `JSONP` requests it can have unwanted side effects. Check  #11
