### ISSUE TITLE
Support requesting binary files (images)

### ISSUE THREAD

**Issue by grompe** [gnuns/AllOrigins#2]
Contents get encoded into textual UTF-16 JavaScript string, changing 0x80-0xFF bytes to 0xFFFD, making it impossible to use for binary data.

**Comment by hezag** [comment]
Return images as base64 strings would be better? Or raw data (AllOrigins would be just a proxy)?
What do you suggest?

**Comment by grompe** [comment]
Raw data is better on bandwidth and CPU, but requires #1 to be implemented.

**Comment by gnuns** [comment]
Done! 
https://allorigins.pw/get?method=raw&url=http://i3.kym-cdn.com/entries/icons/original/000/000/107/awesome-face.png
