### ISSUE TITLE
Cross-Origin Request Blocked: CORS header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by mfaizsyahmi** [gnuns/AllOrigins#21]
As of Firefox 56, the responses from this (and all the other anyorigin-like proxy services) are caught and blocked by the browser for missing the Access-Control-Allow-Origin http response header.

The error message on the console goes like the following:  
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.whateverorigin.org/get?url=<INSERT URL>. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

A relatively quick and easy fix is to add said headers to the response like so:   
`Access-Control-Allow-Origin: *`

**Comment by gnuns** [comment]
Hi, @mfaizsyahmi. AllOrigins already send `Access-Control-Allow-Origin: *` on all requests. Can you provide a example request/page where it's not working?

**Comment by Muhammad-Zaryaab-Shahbaz** [comment]
Its not working and I am getting the same error.
URL: https://www.gunbroker.com/api/items?keywords=arab&Categories=0&FeaturedListing=false&Sort=13

Any help would be appreciated.
