### ISSUE TITLE
https://allorigins.me gives me Nothing here yet :/ ?

### ISSUE THREAD

**Issue by kamilbolka** [gnuns/AllOrigins#22]
I've been integrating AllOrigins with my app today, everything worked as it should, but just recently all my fetch requests returned GET error. From what I can see, this problem is not on my part, it might be the server you're hosting this API on.

![image](https://user-images.githubusercontent.com/22923288/42594515-4373b8e8-8547-11e8-9160-4bc7c80d6105.png)

**Comment by kamilbolka** [comment]
Well it works now... But will it go down randomly again?

**Comment by gnuns** [comment]
Hi, @kamilbolka!
Today I migrated the server to a new datacenter and this caused the downtime.
Everything is back online now! :)

**Comment by godfatherofweb** [comment]
allorigins.me seems to be down today?
