### ISSUE TITLE
ISO-8859-1

### ISSUE THREAD

**Issue by PabloSzx** [gnuns/AllOrigins#3]
I have a big problem, i need to get data from a page that uses iso-8859-1 charset, and when i use getjson, this give me � on all the special characters, can you give at least an example how to use $.ajax so i can try to decode the charset? thank you

**Comment by PabloSzx** [comment]
apparently i could fix this using $.get example, just using 
`$.ajaxSetup({
    contentType: 'application/x-www-form-urlencoded; charset=ISO-8859-1',
    beforeSend: function(jqXHR) {
      jqXHR.overrideMimeType('text/html; charset=ISO-8859-1');
    }
  });`
before i do the $.get

**Comment by gnuns** [comment]
I just added the "charset" parameter to simplify the request in these cases. :smile:

Now we can use: [https://allorigins.us/get?url=http://globo.com&**charset=UTF-8**](https://allorigins.us/get?url=http://globo.com&charset=UTF-8)
