### ISSUE TITLE
allorigins.me seems to be down today?

### ISSUE THREAD

**Issue by godfatherofweb** [gnuns/AllOrigins#31]
_Originally posted by @godfatherofweb in https://github.com/gnuns/AllOrigins/issue_comments#issuecomment-442968580_

**Comment by godfatherofweb** [comment]
thanks, is the old endpoint deprecated and will no longer work?

**Comment by gnuns** [comment]
Unfortunately the old domain has expired and I'm locked out of my registrar's account. :cry: 
So, for now, the old endpoint will not work.

**Comment by godfatherofweb** [comment]
thanks for prompt reply!
