### ISSUE TITLE
raw content (CORS)

### ISSUE THREAD

**Issue by ninconanco** [gnuns/AllOrigins#33]
method=raw seems not working anymore.
Example :
http://api.allorigins.ml/get?url=https%3A//archive.org/
http://api.allorigins.ml/get?method=raw&url=https%3A//archive.org/

**Comment by gnuns** [comment]
Hi, @ninconanco. Thank you for reporting!
I updated the API to support another request methods (38bace54ee9380db7cd45e5cca250418d2882376), but forgot to add this option to the docs!
Please use `http://api.allorigins.ml/raw?url=https%3A//archive.org/` instead.
