### ISSUE TITLE
Handling ERR_CONTENT_LENGTH_MISMATCH 

### ISSUE THREAD

**Issue by inifacebooksatu** [gnuns/allOrigins#34]
I am getting Error: net::ERR_CONTENT_LENGTH_MISMATCH when test fetch https://fantasy.premierleague.com/drf/bootstrap-static on your site (https://allorigins.ml) but have expected result when fetch https://fantasy.premierleague.com/drf/leagues-classic-standings/313?phase=1&le-page=1&ls-page=1

How to deal with this ? or what's going on ?

Update : same case when fetch https://archive.org (ERR_CONTENT_LENGTH_MISMATCH ) but work with https://google.com

**Comment by reviewingcode** [comment]
Same issue as OP.
GET https://api.allorigins.ml/get?url=https%3A%2F%2Fphotos.app.goo.gl%2FbjwsrJRXt7qkoHP1A net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

Issue goes away when running a clone(version 2.0.2). Tested with local and Heroku deployments so far.

**Comment by gnuns** [comment]
Hi, @inifacebooksatu and @reviewingcode. Thank you for reporting!
The error was not related to the code, but a configuration problem on the reverse proxy that powers our public endpoint (api.allorigins.ml). It’s now fixed. ;)

**Comment by Dario326** [comment]
Hi, I am getting this error again

**Comment by gnuns** [comment]
Thanks, @Dario326. Permanently fixed now!

**Comment by kajihh** [comment]
allorigins is down again
