### ISSUE TITLE
Is https://allorigins.ml/ down?

### ISSUE THREAD

**Issue by Teoxoy** [gnuns/allOrigins#35]

**Comment by godfatherofweb** [comment]
looks to be? any update from the team?

**Comment by Teoxoy** [comment]
Not yet.

**Comment by jonaskuske** [comment]
Any alternatives?

**Comment by Teoxoy** [comment]
https://cors-anywhere.herokuapp.com/ but it's rate limited

**Comment by AFunnyMeme** [comment]
Uploaded a mirror on Glitch, results may vary.
https://allorigins.glitch.me

**Comment by Dtinpa** [comment]
Do we at least know the nature of the issue?

**Comment by AFunnyMeme** [comment]
> Do we at least know the nature of the issue?

Domain expired, it was registered on Freenom.

**Comment by gnuns** [comment]
Hi, I just registered a new domain name for the next couple years.
You can use https://allorigins.win/ now.

@Teoxoy @godfatherofweb @jonaskuske @AFunnyMeme @Dtinpa @ninconanco

**Comment by jonaskuske** [comment]
Awesome, thank you! 🚀
