### ISSUE TITLE
API Performance issues

### ISSUE THREAD

**Issue by galliaaa** [gnuns/allOrigins#44]
The allOrigins API is having server problems:

Error codes 504, 500.

**Comment by galliaaa** [comment]
Also getting a 520 error:

The 520 error is used as a "catch-all response for when the origin server returns something unexpected", listing connection resets, large headers, and empty or invalid responses as common triggers. The origin server has refused the connection from Cloudflare.

**Comment by galliaaa** [comment]
Or perhaps this could be the issue:

A cookie associated with a cross-site resource at http://allorigins.win/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by RileyXX** [comment]
I'm having the same issue as of this past week

**Comment by ninconanco** [comment]
Me too

**Comment by galliaaa** [comment]
Does anyone know when this issue might get fixed?

**Comment by elvis7449** [comment]
Same problem

**Comment by gnuns** [comment]
Hi, @galliaaa @RileyXX @elvis7449 @ninconanco @Joontae-Kim. The server is running, but still overloaded. If you are using allOrigins for production, please consider supporting the project on [Patreon](https://www.patreon.com/gnuns) so I'll be able to upgrade the server.

![server usage](https://user-images.githubusercontent.com/981105/67676463-4cab9280-f960-11e9-81ce-1e95cbe37e0d.png)
