### ISSUE TITLE
Error 521

### ISSUE THREAD

**Issue by pascualm4** [gnuns/allOrigins#46]
We have a trouble to render any url using the api. The error is a 521 telling us the server is down. Can you check what happened with the server? Thanks in advance.

**Comment by RileyXX** [comment]
Same problem. Looks like it came back online and was running okay a few days ago after having [performance issues](https://github.com/gnuns/allOrigins/issues/44). Now it looks like it's just completely offline.

**Comment by AdamReznicek** [comment]
Is it alternative to allOrigins or anyOrigins.com? Both is down.

**Comment by galliaaa** [comment]
Is this issue still occurring? @RileyXX  @pascualm4

**Comment by RileyXX** [comment]
> Is this issue still occurring? @RileyXX @pascualm4

Yep

**Comment by gnuns** [comment]
https://github.com/gnuns/allOrigins/issues/44#issuecomment-546912594
