### ISSUE TITLE
It Dosen't work anymore ?

### ISSUE THREAD

**Issue by ajarouih** [gnuns/allOrigins#47]
Hey,  

I built an app using your api and now it doesn't work any more ?

Thanks.

**Comment by galliaaa** [comment]
@ajarouih  I am having the same problem. Hopefully it gets fixed soon

**Comment by ajarouih** [comment]
OK, thanks.

**Comment by gnuns** [comment]
https://github.com/gnuns/allOrigins/issues/44#issuecomment-546912594
