### ISSUE TITLE
JSONP broken, callback=foo has no effect

### ISSUE THREAD

**Issue by bulk88** [gnuns/AllOrigins#5]
The example at https://multiverso.me/AllOrigins/ mentions callback parameter works, this would be for older browsers that dont do CORS and only JSONP. It doesn't in real life, response comes back unwrapped. Commit https://github.com/gnuns/AllOrigins/commit/41d07f257babe93b97e9e744a822e0e48a154b83 seems to have removed JSONP when adding CORS.

**Comment by gnuns** [comment]
Fixed! Thank you for reporting!
