### ISSUE TITLE
Error 521

### ISSUE THREAD

**Issue by kukosek** [gnuns/allOrigins#54]
https://api.allorigins.win
Web server is down

**Comment by savagemode2020** [comment]
Getting CORS error now is there an issue with the server?

**Comment by Muhammad-Zaryaab-Shahbaz** [comment]
I am also facing the same issue.

**Comment by savagemode2020** [comment]
Is this because of the latest Chrome update?

**Comment by kukosek** [comment]
I am using Firefox, the page doesn't load for me at all. So I guess not, the server is probably down.

**Comment by gnuns** [comment]
Fixed! Please consider donating to help me maintain this project: https://www.patreon.com/gnuns
