### ISSUE TITLE
Chinese Characters garbled

### ISSUE THREAD

**Issue by zolrath** [gnuns/allOrigins#73]
Hello!
I'm using this package to retrieve page titles and it's come to my attention that it doesn't seem to keep the encoding of Chinese characters.

https://api.allorigins.win/get?url=https://zhidao.baidu.com/question/509882629.html

I've tried raw and specifying various encodings:

https://api.allorigins.win/raw?url=https://zhidao.baidu.com/question/509882629.html&charset=UTF-8

Is there something I'm missing to preserve the text?

Thanks for making this great project!

**Comment by gnuns** [comment]
Hi, @zolrath! 
Thank you for reporting, indeed there was a [bug](https://github.com/gnuns/allOrigins/commit/41214bfdb8fdf64478ec111410e65302bc7cb48e) on the `charset` feature.
Now it should work like expected. Please try again using the `gbk` encoding:

- https://api.allorigins.win/get?url=https://zhidao.baidu.com/question/509882629.html&charset=gbk
- https://api.allorigins.win/raw?url=https://zhidao.baidu.com/question/509882629.html&charset=gbk
