### ISSUE TITLE
Params from requests are dropped

### ISSUE THREAD

**Issue by FrantisekHrdina** [gnuns/allOrigins#74]
Hi, I am sending this request
`curl -X GET "https://api.allorigins.win/raw?url=https://api.nhle.com/stats/rest/en/skater/summary?isAggregate=false&isGame=false&sort=%5B%7B%22property%22:%22points%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22goals%22,%22direction%22:%22DESC%22%7D,%7B%22property%22:%22assists%22,%22direction%22:%22DESC%22%7D%5D&start=0&limit=50&factCayenneExp=gamesPlayed%3E=1&cayenneExp=gameTypeId=2%20and%20nationalityCode=%22CZE%22%20and%20seasonId%3C=20202021%20and%20seasonId%3E=20202021"`

but the response is different from expected, probably some parameters of the request are dropped by proxy. I am not sure, if I am using it well, or if it is a bug. Can you give me some advice on preventing dropping those params, if I am doing it badly? Thank you.

**Comment by gnuns** [comment]
Hi, @FrantisekHrdina!
You need to encode the target URL before using it as a parameter. You can do this using JS's `encodeURIComponent()` or something like [urldecode.org](https://urldecode.org/?text=https%253A%252F%252Fapi.nhle.com%252Fstats%252Frest%252Fen%252Fskater%252Fsummary%253FisAggregate%253Dfalse%2526isGame%253Dfalse%2526sort%253D%25255B%25257B%252522property%252522%253A%252522points%252522%252C%252522direction%252522%253A%252522DESC%252522%25257D%252C%25257B%252522property%252522%253A%252522goals%252522%252C%252522direction%252522%253A%252522DESC%252522%25257D%252C%25257B%252522property%252522%253A%252522assists%252522%252C%252522direction%252522%253A%252522DESC%252522%25257D%25255D%2526start%253D0%2526limit%253D50%2526factCayenneExp%253DgamesPlayed%25253E%253D1%2526cayenneExp%253DgameTypeId%253D2%252520and%252520nationalityCode%253D%252522CZE%252522%252520and%252520seasonId%25253C%253D20202021%252520and%252520seasonId%25253E%253D20202021&mode=decode).

e.g.:
```sh
curl -X GET "https://api.allorigins.win/raw?url=https%3A%2F%2Fapi.nhle.com%2Fstats%2Frest%2Fen%2Fskater%2Fsummary%3FisAggregate%3Dfalse%26isGame%3Dfalse%26sort%3D%255B%257B%2522property%2522%3A%2522points%2522%2C%2522direction%2522%3A%2522DESC%2522%257D%2C%257B%2522property%2522%3A%2522goals%2522%2C%2522direction%2522%3A%2522DESC%2522%257D%2C%257B%2522property%2522%3A%2522assists%2522%2C%2522direction%2522%3A%2522DESC%2522%257D%255D%26start%3D0%26limit%3D50%26factCayenneExp%3DgamesPlayed%253E%3D1%26cayenneExp%3DgameTypeId%3D2%2520and%2520nationalityCode%3D%2522CZE%2522%2520and%2520seasonId%253C%3D20202021%2520and%2520seasonId%253E%3D20202021"
```
