### ISSUE TITLE
I'm want get filesize

### ISSUE THREAD

**Issue by TechComet** [gnuns/AllOrigins#8]
Hi,

I'm want get filesize

**Comment by gnuns** [comment]
I just added this feature on #9. Now you can get file size on the status.content_length and Content-Length header. You can also get the file size before downloading, using `method=info` to request only the information about the file.

Example:
http://allorigins.us/get?method=info&url=https://archive.org/images/WaybackLogoSmall.png

Returns:
```js
{
  "url": "https://archive.org/images/WaybackLogoSmall.png",
  "content_type": "image/png",
  "content_length": 14278, // file size in bytes
  "http_code": 200
}
```
