### ISSUE TITLE
Service Down?

### ISSUE THREAD

**Issue by rolandoscott** [gnuns/allOrigins#89]
https://api.allorigins.win is timing out.

![image](https://user-images.githubusercontent.com/17934629/135193342-914347f4-f75e-459f-b2b4-1641f26d45fa.png)

**Comment by bulk88** [comment]
Same here timeout/CF error screen here.

**Comment by ParraAlonso** [comment]
Got same error here... hope it gets solved

**Comment by jesus-itravel** [comment]
Seems to be solved now, at least to me.

**Comment by Sebi94nbg** [comment]
I can confirm, that it's working again. Thanks to whoever/whatever it fixed. :D

**Comment by gnuns** [comment]
Hi, @rolandoscott @bulk88 @ParraAlonso @jesus-itravel @Sebi94nbg @N0itx @johnsmithm @jclarkkoala @WeGoToMars @adamvx @samoslag!
I had to migrate to a new server. If you can, please consider donating ANY amount to help me maintain this public and free instance online for everyone. 

- [Patreon](https://www.patreon.com/gnuns)
- [Liberapay](https://liberapay.com/gnuns)
- [Paypal](https://www.paypal.com/donate/?hosted_button_id=7S3KJ8CA43DX6)
- [Ko-fi](https://ko-fi.com/gnuns)

Thank you!
